import os
import openai
from PIL import Image
import streamlit as st
# openai.api_key = os.environ.get('OpenAI_API_Key')

openai.api_key = "xxxxxx"

@st.cache(persist=True,allow_output_mutation=True,show_spinner=False,suppress_st_warning=True)
def openai_image(prompt):
    response = openai.Image.create(
      prompt=prompt,
      n=1,
      size="256x256"
    )
    image_url = response['data'][0]['url']
    return image_url


st.title("一起来玩AI绘画吧~")
st.markdown("以下调用的是OpenAI的DALL-E 2模型，可以生成一些很有意思的图片哦~")


input_text = st.text_area("在下面输入文字描述.. 🙋",height=50)
image_button = st.button("见证奇迹的时刻 🚀")

if image_button and input_text.strip() != "":
    with st.spinner("Loading...💫"):
        image_url = openai_image(input_text)
        st.image(image_url, caption='Generated by OpenAI')
# else:
    # st.warning("Please enter something! ⚠")

# st.markdown("<br><hr><center>Made with ❤️ by <a href='mailto:ralhanprateek@gmail.com?subject=ChatGPT + DALL-E WebApp!&body=Please specify the issue you are facing with the app.'><strong>Prateek Ralhan</strong></a></center><hr>", unsafe_allow_html=True)
st.markdown("<style> footer {visibility: hidden;} </style>", unsafe_allow_html=True)